---
- hosts: agent
  become: true
  vars:
   ansible_become_pass: pooja
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Git on Ubuntu
      apt:
        name: git
        state: present

    - name: Install JDK on Ubuntu
      apt:
        name: default-jdk
        state: present

    - name: Install Chromium browser on Ubuntu
      apt:
        name: chromium-browser
        state: present

    - name: Install Chromium Driver on Ubuntu
      apt:
        name: chromium-chromedriver
        state: present

    - name: Copy agent.jar file to Ubuntu
      copy:
        src: /home/pooja/masterdata/agent.jar
        dest: /home/pooja/agent.jar
        mode: '0755'

    - name: Run apt update after installation
      apt:
        update_cache: yes

    - name: Add Docker GPG key
      apt_key: url=https://download.docker.com/linux/ubuntu/gpg

    - name: Add Docker APT repository
      apt_repository:
       repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

    - name: Install list of packages
      apt:
       name: "{{ item }}"
       state: present
       update_cache: yes
      loop:
       - apt-transport-https
       - ca-certificates - curl
       - software-properties-common
       - docker-ce
